import type { Metadata } from "next"
import { Inter } from "next/font/google"

import Providers from "@/app/providers"
import { LayoutProps } from "@/types"

import "./globals.css"

// eslint-disable-next-line new-cap
const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en" className="bg-background">
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
